### ISSUE TITLE
Trying to test the interface but got error

### ISSUE THREAD

**Issue by ReynardoEW** [adrianceding/simple_binance_futures#1]
FT 2021.07

Latest commit from this repo

This error shows up every time
freqtrade.strategy.strategy_wrapper - ERROR - Unexpected error unsupported operand type(s) for +: 'float' and 'NoneType' calling <bound method IFutures.bot_loop_start of <SimpleBinanceFutures.SimpleBinanceFutures object at 0x7f1a8d89cc88>>
Traceback (most recent call last):
  File "/root/freqtrade/freqtrade/strategy/strategy_wrapper.py", line 17, in wrapper
    return f(*args, **kwargs)
  File "/root/freqtrade/user_data/strategies/interface_futures_binance.py", line 72, in bot_loop_start
    self.prepare_futures()
  File "/root/freqtrade/user_data/strategies/interface_futures_binance.py", line 85, in prepare_futures
    self.reset_leverage()
  File "/root/freqtrade/user_data/strategies/interface_futures_binance.py", line 123, in reset_leverage
    stoploss = max(-1 / self._leverage + x["maintenanceMarginPercentage"], self.stoploss)
TypeError: unsupported operand type(s) for +: 'float' and 'NoneType'

I tested the sample strategy because I got this error on other strategy too it seems like it's trying to check for maintenance margin percent but because there's no open position it doesn't return anything back

**Comment by ReynardoEW** [comment]
By adding check if the maintenanceMarginPercentage is none, I was able to solve this problem but it might be the wrong solution

**Comment by adrianceding** [comment]
> By adding check if the maintenanceMarginPercentage is none, I was able to solve this problem but it might be the wrong solution

Please provide the returned data of fetch_positions. Otherwise I cannot reproduce
